### ISSUE TITLE
Missing airportitlwm

### ISSUE THREAD

**Issue by halal-beef** [AlbinoGiraffe/Latitude-7390-Hackintosh#1]
kext needed for internet

**Comment by AlbinoGiraffe** [comment]
I installed a Fenvi wifi card, which works the same as a genuine Apple Card, so no kexts needed

**Comment by halal-beef** [comment]
oh okay, imo you should update the readme to update ur hardware

**Comment by AlbinoGiraffe** [comment]
But it _is_ in the README lol

**Comment by halal-beef** [comment]
Yeah, realised sorry
