### ISSUE TITLE
shutdown issue in Ventura

### ISSUE THREAD

**Issue by occparty** [AlbinoGiraffe/Latitude-7390-Hackintosh#2]
hey Sir, I have a latitude 7390 too but with a touchscreen, and I built an EFI from scratch with Dortania's Guide.
My problem is that I can not turn off 7390 with normal step: when I click shutdown, the notebook restarts instead. So I try your whole EFI except my USBport.kext; it can boot into Ventura 13.2.1 smoothly but still it returns restart when I shutdown.

Do you encounter the same problem? Or can you give me some advice?
Thank you!

I've tried https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html and acpi guide in
https://github.com/5T33Z0/OC-Little-Translated

**Comment by AlbinoGiraffe** [comment]
Hi, my laptop doesn’t have a touchscreen so I’m not entirely sure why yours would restart. Maybe macOS crashes when turning off the display since the touchscreen doesn’t have drivers?

**Comment by occparty** [comment]
yeah, you are right, the problem seems lie in my faulty USB mapping, bro your EFI should have no problem.
Sorry for commit a issue, you can close this one.


Thanks again!!
btw, the recent file I downloaded here seems still OC 0.8.4?

**Comment by AlbinoGiraffe** [comment]
It might still be on 0.8.4. I rarely use this laptop now but I'll see if I have time to update it, thanks!
